---
- name: Instalar aplicaciones básicas
  hosts: ubuntu1,ubuntu2
  become: yes
  
  tasks:
    - name: Actualizar apt cache
      apt:
        update_cache: yes
      
    - name: Instalar paquetes básicos
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - python3
        - python3-pip
        - git
        
    - name: Verificar instalaciones
      command: "{{ item }} --version"
      register: versiones
      loop:
        - nginx
        - python3
      changed_when: false

    - name: Mostrar versiones
      debug:
        var: versiones.results
