---
- hosts: all
  gather_facts: no
  tasks:
    - name: Echo connection info
      debug:
        msg: "Connecting to {{ inventory_hostname }} as {{ ansible_user }}"
    
    - name: Ping host
      ping:
